openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Apifecol"
  description: "Documentaci贸n API Facturaci贸n Electr贸nica DIAN UBL2.1"
  contact:
    email: "soyjuanbautista0@gmail.com"
  license:
    name: "GNU General Public License v3.0"
    url: "https://github.com/juanbautista0/apifecol/blob/main/LICENSE"
servers:
  - url: "http://localhost:8025"
    description: "Identity Server test API"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /info:
    get:
      tags:
        - "Status"
      summary: "(ES): Obtener estado de API. (EN): Get API status."
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /login/login:
    post:
      tags:
        - "Login"
      summary: "(ES): Obtener token de sesi贸n. (EN): Get session token."
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                tenancy:
                  type: string
                email:
                  type: string
                password:
                  type: string
                NIT:
                  type: string
            example: # Sample object
              tenancy: "apifecol"
              email: "juan.bautista@plenusservices.com"
              password: "your_password"
              NIT: "901004305"
      responses:
        202:
          description: "Accepted"
        403:
          description: "Access permission denied"
        500:
          description: "Server error"
  /listings/rows/{source}/{id}:
    get:
      tags:
        - "Listings"
      summary: "(ES): Listado de recursos. (EN): Resources listings."
      produces:
      - "application/json"
      parameters:
      - name: "source"
        in: "path"
        description: "Nombre de tabla/recurso"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        description: "ID de recurso"
        required: false
        default: 0
        type: "integer"
        format: "int"
      responses:
        200:
          description: "Ok"
        401:
          description: "Unauthorized"
        404:
          description: "Not Found "
        500:
          description: "Server error"
