openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Apifecol"
  description: "API facturación electrónica"
  contact: 
    email: "soyjuanbautista0@gmail.com"
  license:
    name: "GNU General Public License v3.0"
    url: "https://github.com/juanbautista0/apifecol/blob/main/LICENSE"
servers:
  - url: "http://localhost/apifecol"
    description: "Identity Server test API"
components:
  securitySchemes:
    # See https://demo.identityserver.io/ for configuration details.
    identity_server_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "https://demo.identityserver.io/connect/authorize"
          scopes:
            api: "api"
security:
  - identity_server_auth:
      - api
paths:
  /info:
    get:
      tags:
        - "Status"
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
  /login/login:
     post:
      tags:
      - "Login"
      summary: "Log in and get a token."
      description: ""
      operationId: "placeOrder"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "order placed for purchasing the pet"
        required: true
        schema:
          type: object
          properties:
            tenancy:
              type: string
            email:
                type: string
            password:
                type: string
            NIT:
                type: string
            example:   # Sample object
              tenancy: "Plenus"
              email: "soyjuanbautista0@gmail.com"
      
      responses:
        "202":
          description: "Accepted"
          schema:
        "403":
          description: "Access permission denied"